version: '3.8'
services:
    client:
        build:
            context: client
            dockerfile: Dockerfile.dev
        ports:
            - '3000:3000'
        volumes:
            - ./client/src:/app/src
    api:
        build:
            context: server
            dockerfile: Dockerfile.dev
        ports:
            - '8080:8080'
        volumes:
            - ./server/src:/app/src
    # db:
    #     image: mongo
    #     environment:
    #     volumes:
    #     ports:
    #         - '27017:27017'
